module.exports = {

    SOCKET_CONNECTION: "connection",
    SOCKET_DISCONNECTION: "disconnect",
    SOCKET_RECONNECT: "re-connect",

    SOCKET_DATE_FIND_TARGET_AVAILABLE: "date-find-target-available",
    SOCKET_DATE_NEW_ANSWER: "SOCKET_DATE_NEW_ANSWER",
    SOCKET_DATE_RECEIVE_ANSWER: "SOCKET_DATE_RECEIVE_ANSWER",
    SOCKET_DATE_RECEIVE_OFFER: "SOCKET_DATE_RECEIVE_OFFER",
    SOCKET_DATE_ICE_CANDIDATE: "SOCKET_DATE_ICE_CANDIDATE",

    SOCKET_DATE_RECEIVE_ICE_CANDIDATE: "SOCKET_DATE_RECEIVE_ICE_CANDIDATE",
}